import { migrate } from "drizzle-orm/better-sqlite3/migrator";
import { db } from "./index.js";
import path from "path";
import { fileURLToPath } from "url";
import { existsSync } from "fs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/**
 * Run all pending Drizzle ORM migrations.
 * 
 * Migration files are generated by `drizzle-kit generate` and stored in
 * `lib/db/migrations/`. On first run (no migrations folder), falls back
 * to `drizzle-kit push` behavior (schema auto-sync).
 * 
 * Usage: import { runMigrations } from "@workspace/db/migrate";
 *        runMigrations();
 */
export function runMigrations() {
  const migrationsFolder = path.resolve(__dirname, "../migrations");

  if (!existsSync(migrationsFolder)) {
    console.log("[db] No migrations folder found — using schema push mode");
    return false;
  }

  try {
    migrate(db, { migrationsFolder });
    console.log("[db] Migrations applied successfully");
    return true;
  } catch (err) {
    console.error("[db] Migration failed:", err);
    throw err;
  }
}
